P8105_hw4_hc3212
================
Hening cui
2021/10/14

## Homework 3

## Problem 1

**Load and describe instacart data set.**

``` r
data("instacart")
```

The instacart data set contains 1384617 observations and 15 variables.
The data set is in a “long” format.The variable contains
add_to_cart_order, aisle, aisle_id, days_since_prior_order, department,
department_id, eval_set, order_dow, order_hour_of_day, order_id,
order_number, product_id, product_name, reordered, user_id. Every user
has an unique user id, and each order has an unique order id. Every
product was assigned a product id, the aisle together with aisle id
showed the category of product. Product belongs to different department
and could distinguished by department id. Reorder indicated whether the
product has been ordered before, with 1 means yes, 0 means no. Order dow
and order hour of day means at which hour in the weekday it was ordered.
Take row one as an example.

| order_id | product_id | add_to_cart_order | reordered | user_id | eval_set | order_number | order_dow | order_hour_of_day | days_since_prior_order | product_name                                  | aisle_id | department_id | aisle                | department   |
|---------:|-----------:|------------------:|----------:|--------:|:---------|-------------:|----------:|------------------:|-----------------------:|:----------------------------------------------|---------:|--------------:|:---------------------|:-------------|
|        1 |      49302 |                 1 |         1 |  112108 | train    |            4 |         4 |                10 |                      9 | Bulgarian Yogurt                              |      120 |            16 | yogurt               | dairy eggs   |
|        1 |      11109 |                 2 |         1 |  112108 | train    |            4 |         4 |                10 |                      9 | Organic 4% Milk Fat Whole Milk Cottage Cheese |      108 |            16 | other creams cheeses | dairy eggs   |
|        1 |      10246 |                 3 |         0 |  112108 | train    |            4 |         4 |                10 |                      9 | Organic Celery Hearts                         |       83 |             4 | fresh vegetables     | produce      |
|        1 |      49683 |                 4 |         0 |  112108 | train    |            4 |         4 |                10 |                      9 | Cucumber Kirby                                |       83 |             4 | fresh vegetables     | produce      |
|        1 |      43633 |                 5 |         1 |  112108 | train    |            4 |         4 |                10 |                      9 | Lightly Smoked Sardines in Olive Oil          |       95 |            15 | canned meat seafood  | canned goods |
|        1 |      13176 |                 6 |         0 |  112108 | train    |            4 |         4 |                10 |                      9 | Bag of Organic Bananas                        |       24 |             4 | fresh fruits         | produce      |

Row one means in order 1, user 112108 add 4 boxes of Bulgarian yogurt
first in to the cart. This product was also ordered 10 days before.
Bulgarian yogurt was identified as 49302 and belongs to yogurt category
(id 120) in dairy eggs department (id 16). The order was at 10 o’clock
in Thursday.

**How many aisles are there, and which aisles are the most items ordered
from?**

``` r
instacart %>% 
  pull(aisle_id) %>% 
  n_distinct()
```

    ## [1] 134

``` r
instacart %>% 
  group_by(aisle_id, aisle) %>% 
  summarize(n_item = n()) %>% 
  arrange(desc(n_item))
```

    ## `summarise()` has grouped output by 'aisle_id'. You can override using the `.groups` argument.

    ## # A tibble: 134 × 3
    ## # Groups:   aisle_id [134]
    ##    aisle_id aisle                         n_item
    ##       <int> <chr>                          <int>
    ##  1       83 fresh vegetables              150609
    ##  2       24 fresh fruits                  150473
    ##  3      123 packaged vegetables fruits     78493
    ##  4      120 yogurt                         55240
    ##  5       21 packaged cheese                41699
    ##  6      115 water seltzer sparkling water  36617
    ##  7       84 milk                           32644
    ##  8      107 chips pretzels                 31269
    ##  9       91 soy lactosefree                26240
    ## 10      112 bread                          23635
    ## # … with 124 more rows

There totally 134 aisles, fresh_vegetables(id:83) had most items ordered
from.

**Make a plot that shows the number of items ordered in each aisle,
limiting this to aisles with more than 10000 items ordered. Arrange
aisles sensibly, and organize your plot so others can read it.**

``` r
instacart %>% 
  group_by(aisle_id, aisle) %>% 
  summarize(n_item = n()) %>% 
  filter(n_item > 10000) %>% 
  arrange(desc(n_item)) %>% 
  ggplot() +
  geom_bar(aes(x = n_item, y = aisle, fill = aisle),stat = 'identity', alpha = 0.5) +
  labs(
    title = "No. of items vs Aisle",
    y = "Aisle", 
    x = "No. of item",
  ) +
  scale_x_continuous( 
    breaks = c(10000, 20000, 40000, 80000, 120000)
    ) +
  theme(
    legend.position = 'none',
    axis.text.y = element_text(size = 6),
    axis.text.x = element_text(size = 5))
```

<img src="P8105_hw3_hc3212_files/figure-gfm/aisle_plot-1.png" width="90%" />

**Make a table showing the three most popular items in each of the
aisles “baking ingredients”, “dog food care”, and “packaged vegetables
fruits”. Include the number of times each item is ordered in your
table.**

``` r
backing = 
  instacart %>% 
  filter(aisle == "baking ingredients") %>% 
  group_by(aisle, product_name) %>% 
  summarize(n_item = n()) %>% 
  arrange(desc(n_item)) %>% 
  head(3)

dog = 
  instacart %>% 
  filter(aisle == c("dog food care")) %>% 
  group_by(aisle, product_name) %>% 
  summarize(n_item = n()) %>% 
  arrange(desc(n_item)) %>% 
  head(3)  

vegetable = 
  instacart %>% 
  filter(aisle == "packaged vegetables fruits") %>% 
  group_by(aisle, product_name) %>% 
  summarize(n_item = n()) %>% 
  arrange(desc(n_item)) %>% 
  head(3)   

bind_rows(backing, dog, vegetable) %>% 
  knitr::kable()
```

| aisle                      | product_name                                  | n_item |
|:---------------------------|:----------------------------------------------|-------:|
| baking ingredients         | Light Brown Sugar                             |    499 |
| baking ingredients         | Pure Baking Soda                              |    387 |
| baking ingredients         | Cane Sugar                                    |    336 |
| dog food care              | Snack Sticks Chicken & Rice Recipe Dog Treats |     30 |
| dog food care              | Organix Chicken & Brown Rice Recipe           |     28 |
| dog food care              | Small Dog Biscuits                            |     26 |
| packaged vegetables fruits | Organic Baby Spinach                          |   9784 |
| packaged vegetables fruits | Organic Raspberries                           |   5546 |
| packaged vegetables fruits | Organic Blueberries                           |   4966 |

**Make a table showing the mean hour of the day at which Pink Lady
Apples and Coffee Ice Cream are ordered on each day of the week; format
this table for human readers (i.e. produce a 2 x 7 table).**

``` r
instacart %>% 
  filter(product_name == c("Pink Lady Apples", "Coffee Ice Cream")) %>% 
  select(order_dow, order_hour_of_day, product_name) %>% 
  group_by(product_name, order_dow) %>% 
  summarize(meant = mean(order_hour_of_day)) %>% 
  mutate(
    order_dow = case_when(
      order_dow == 1 ~ "Monday",
      order_dow == 2 ~ "Tuesday",
      order_dow == 3 ~ "Wednesday",
      order_dow == 4 ~ "Thursday",
      order_dow == 5 ~ "Friday",
      order_dow == 6 ~ "Saturday",
      order_dow == 0 ~ "Sunday",
    )
  ) %>% 
  pivot_wider(
    names_from = order_dow,
    values_from = meant
  ) %>% 
  knitr::kable()
```

    ## Warning in product_name == c("Pink Lady Apples", "Coffee Ice Cream"): longer
    ## object length is not a multiple of shorter object length

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

| product_name     |   Sunday |   Monday |  Tuesday | Wednesday | Thursday |   Friday | Saturday |
|:-----------------|---------:|---------:|---------:|----------:|---------:|---------:|---------:|
| Coffee Ice Cream | 13.22222 | 15.00000 | 15.33333 |   15.4000 | 15.16667 | 10.33333 | 12.35294 |
| Pink Lady Apples | 12.25000 | 11.67857 | 12.00000 |   13.9375 | 11.90909 | 13.86957 | 11.55556 |
